[2024-06-13T05:45:55.425+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-13T05:45:55.483+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: welcome_dag.print_quote manual__2024-06-13T05:45:20.358550+00:00 [queued]>
[2024-06-13T05:45:55.503+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: welcome_dag.print_quote manual__2024-06-13T05:45:20.358550+00:00 [queued]>
[2024-06-13T05:45:55.504+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-13T05:45:55.571+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): print_quote> on 2024-06-13 05:45:20.358550+00:00
[2024-06-13T05:45:55.580+0000] {standard_task_runner.py:63} INFO - Started process 81 to run task
[2024-06-13T05:45:55.588+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'welcome_dag', 'print_quote', 'manual__2024-06-13T05:45:20.358550+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/welcome-dag.py', '--cfg-path', '/tmp/tmp0puwztbw']
[2024-06-13T05:45:55.591+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask print_quote
[2024-06-13T05:45:55.708+0000] {task_command.py:426} INFO - Running <TaskInstance: welcome_dag.print_quote manual__2024-06-13T05:45:20.358550+00:00 [running]> on host 2465249412d9
[2024-06-13T05:45:55.892+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='welcome_dag' AIRFLOW_CTX_TASK_ID='print_quote' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T05:45:20.358550+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-13T05:45:20.358550+00:00'
[2024-06-13T05:45:55.894+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-13T05:45:57.885+0000] {logging_mixin.py:188} INFO - Quote of the day:"I'm selfish, impatient and a little insecure. I make mistakes, I am out of control and at times hard to handle. But if you can't handle me at my worst, then you sure as hell don't deserve me at my best."
[2024-06-13T05:45:57.897+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-13T05:45:57.899+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-13T05:45:57.971+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=welcome_dag, task_id=print_quote, run_id=manual__2024-06-13T05:45:20.358550+00:00, execution_date=20240613T054520, start_date=20240613T054555, end_date=20240613T054557
[2024-06-13T05:45:58.121+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-13T05:45:58.226+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-13T05:45:58.233+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
